### ISSUE TITLE
/actuator/info 访问报错

### ISSUE THREAD

**Issue by comeontom** [deepexi/generator-deepexi-spring-cloud#5]
![image](https://user-images.githubusercontent.com/3394013/62704157-4e2e8400-ba1d-11e9-810e-b2bdb407ebd1.png)

**Comment by comeontom** [comment]
![image](https://user-images.githubusercontent.com/3394013/62704182-5c7ca000-ba1d-11e9-96e1-9046cb567ef1.png)

**Comment by taccisum** [comment]
actuator/info默认是没开放的，你访问actuator/health试试
