### ISSUE TITLE
邮箱没看到呢

### ISSUE THREAD

**Issue by zk20170125** [deepexi/generator-deepexi-spring-cloud#7]
邮箱多少

**Comment by taccisum** [comment]
你看boss直聘上谁跟你聊的，发给他


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: zk20170125 <notifications@github.com>
发送时间: 2019年8月15日 14:31
收件人: deepexi/generator-deepexi-spring-cloud <generator-deepexi-spring-cloud@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[deepexi/generator-deepexi-spring-cloud] 邮箱没看到呢 (#7)




邮箱多少
